In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Use relative path instead of absolute path
data_file = 'ObesityDataSet_raw_and_data_sinthetic.csv'
df = pd.read_csv(data_file)

In [175]:
# Load Dataset
df = pd.read_csv(r'C:\Users\Emre\Desktop\superlig\ObesityDataSet_raw_and_data_sinthetic.csv')

Dataset Information

This dataset include data for the estimation of obesity levels in individuals from the countries of Mexico, Peru and Colombia, based on their eating habits and physical condition. The data contains 17 attributes and 2111 records, the records are labeled with the class variable NObesity (Obesity Level), that allows classification of the data using the values of Insufficient Weight, Normal Weight, Overweight Level I, Overweight Level II, Obesity Type I, Obesity Type II and Obesity Type III. 77% of the data was generated synthetically using the Weka tool and the SMOTE filter, 23% of the data was collected directly from users through a web platform.

Gender: Feature, Categorical, "Gender"

Age : Feature, Continuous, "Age"

Height: Feature, Continuous

Weight: Feature Continuous

family_history_with_overweight: Feature, Binary, " Has a family member suffered or suffers from overweight? "

FAVC : Feature, Binary, " Do you eat high caloric food frequently? "

FCVC : Feature, Integer, " Do you usually eat vegetables in your meals? "

NCP : Feature, Continuous, " How many main meals do you have daily? "

CAEC : Feature, Categorical, " Do you eat any food between meals? "

SMOKE : Feature, Binary, " Do you smoke? "

CH2O: Feature, Continuous, " How much water do you drink daily? "

SCC: Feature, Binary, " Do you monitor the calories you eat daily? "

FAF: Feature, Continuous, " How often do you have physical activity? "

TUE : Feature, Integer, " How much time do you use technological devices such as cell phone, videogames, television, computer and others? "

CALC : Feature, Categorical, " How often do you drink alcohol? "

MTRANS : Feature, Categorical, " Which transportation do you usually use? "

NObeyesdad : Target, Categorical, "Obesity level"

In [176]:
# Display Sample Data
df.sample(5)

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
742,18.000000,Male,1.719827,52.289828,Sometimes,yes,1.202075,3.000000,no,no,1.927976,yes,0.023574,1.747256,Sometimes,Public_Transportation,Insufficient_Weight
447,19.000000,Male,1.800000,87.000000,Sometimes,yes,2.000000,4.000000,no,no,2.000000,yes,2.000000,1.000000,Sometimes,Public_Transportation,Overweight_Level_I
1335,18.729566,Male,1.855433,112.875283,Sometimes,yes,2.000000,2.427137,no,no,2.574073,yes,1.000000,2.000000,Sometimes,Public_Transportation,Obesity_Type_I
1407,21.895468,Female,1.644560,88.119139,no,yes,2.693859,1.000283,no,no,3.000000,yes,1.201403,1.612432,Sometimes,Public_Transportation,Obesity_Type_I
1256,18.000000,Male,1.791174,108.960600,no,yes,2.000000,1.086870,no,no,2.279124,yes,1.000000,1.609773,Sometimes,Public_Transportation,Obesity_Type_I

In [177]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   float64
 1   Gender                          2111 non-null   object
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [178]:
# Statistical Summary
df.describe()

,Age,Height,Weight,FCVC,NCP,CH2O,FAF,TUE
count,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000,2111.000000
mean,24.312600,1.701677,86.586058,2.419043,2.685628,2.008011,1.010298,0.657866
std,6.345968,0.093305,26.191172,0.533927,0.778039,0.612953,0.850592,0.608927
min,14.000000,1.450000,39.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,19.947192,1.630000,65.473343,2.000000,2.658738,1.584812,0.124505,0.000000
50%,22.777890,1.700499,83.000000,2.385502,3.000000,2.000000,1.000000,0.625350
75%,26.000000,1.768464,107.430682,3.000000,3.000000,2.477420,1.666678,1.000000
max,61.000000,1.980000,173.000000,3.000000,4.000000,3.000000,3.000000,2.000000

In [179]:
# Display Last 5 Rows
df.tail()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [180]:
# Check Missing Values
df.isna().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [181]:
# Check Duplicate Rows
df.duplicated().sum()

np.int64(24)

In [182]:
# Remove Duplicate Rows
df.drop_duplicates(inplace=True)

In [183]:
# Dataset Info After Cleaning
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2087 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2087 non-null   float64
 1   Gender                          2087 non-null   object
 2   Height                          2087 non-null   float64
 3   Weight                          2087 non-null   float64
 4   CALC                            2087 non-null   object
 5   FAVC                            2087 non-null   object
 6   FCVC                            2087 non-null   float64
 7   NCP                             2087 non-null   float64
 8   SCC                             2087 non-null   object
 9   SMOKE                           2087 non-null   object
 10  CH2O                            2087 non-null   float64
 11  family_history_with_overweight  2087 non-null   object
 12  FAF                             2087 non-null   float64
 13  TUE                             2087 non-null   float64
 14  CAEC                            2087 non-null   object
 15  MTRANS                          2087 non-null   object
 16  NObeyesdad                      2087 non-null   object
dtypes: float64(8), object(9)
memory usage: 293.5+ KB

In [184]:
# Display Data After Cleaning
df.tail()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
2106,20.976842,Female,1.710730,131.408528,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,21.982942,Female,1.748584,133.742943,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,22.524036,Female,1.752206,133.689352,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,24.361936,Female,1.739450,133.346641,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,23.664709,Female,1.738836,133.472641,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [185]:
# Data Type Conversions and Feature Engineering
df['Age'] = df['Age'].astype(int)  # Convert Age to integer
df['Height'] = df['Height'].round(2)  # Round Height to 2 decimals
df['Weight'] = df['Weight'].round(2)  # Round Weight to 2 decimals

# Calculate BMI (Body Mass Index)
df['BMI'] = (df['Weight'] / (df['Height'] ** 2)).round(2)

In [186]:
# Display Updated Data
df.tail()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,BMI
2106,20,Female,1.71,131.41,Sometimes,yes,3.0,3.0,no,no,1.728139,yes,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III,44.94
2107,21,Female,1.75,133.74,Sometimes,yes,3.0,3.0,no,no,2.005130,yes,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III,43.67
2108,22,Female,1.75,133.69,Sometimes,yes,3.0,3.0,no,no,2.054193,yes,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III,43.65
2109,24,Female,1.74,133.35,Sometimes,yes,3.0,3.0,no,no,2.852339,yes,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III,44.04
2110,23,Female,1.74,133.47,Sometimes,yes,3.0,3.0,no,no,2.863513,yes,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III,44.08

In [187]:
# Check Unique Values in Each Column
for column in df.columns:
    print(f"\n{column} column unique values:")
    print(df[column].unique())

Age column unique values:
[21 23 27 22 29 24 26 41 30 52 20 19 31 39 17 25 55 38 18 15 61 44 34 36
 32 35 40 45 33 51 56 28 16 37 14 42 50 43 46 47]

Gender column unique values:
['Female' 'Male']

Height column unique values:
[1.62 1.52 1.8  1.78 1.5  1.64 1.72 1.85 1.65 1.77 1.7  1.93 1.53 1.71
 1.69 1.6  1.75 1.68 1.58 1.79 1.56 1.67 1.66 1.81 1.82 1.55 1.61 1.63
 1.76 1.57 1.88 1.87 1.89 1.74 1.83 1.92 1.73 1.84 1.91 1.48 1.59 1.54
 1.9  1.86 1.45 1.98 1.51 1.46 1.49 1.95 1.94]

Weight column unique values:
[ 64.    56.    77.   ... 131.41 133.69 133.35]

CALC column unique values:
['no' 'Sometimes' 'Frequently' 'Always']

FAVC column unique values:
['no' 'yes']

FCVC column unique values:
[2.       3.       1.       2.450218 2.880161 2.00876  2.596579 2.591439
 2.392665 1.123939 2.027574 2.658112 2.88626  2.714447 2.750715 1.4925
 2.205439 2.059138 2.310423 2.823179 2.052932 2.596364 2.767731 2.815157
 2.737762 2.568063 2.524428 2.971574 1.0816   1.270448 1.344854 2.959658
 2.725282 2.844607 2.44004  2.432302 2.592247 2.449267 2.929889 2.015258
 1.031149 1.592183 1.21498  1.522001 2.703436 2.362918 2.14084  2.5596
 2.336044 1.813234 2.724285 2.71897  1.133844 1.757466 2.979383 2.204914
 2.927218 2.88853  2.890535 2.530066 2.241606 1.003566 2.652779 2.897899
 2.483979 2.945967 2.478891 2.784464 1.005578 2.938031 2.842102 1.889199
 2.943749 2.33998  1.950742 2.277436 2.371338 2.984425 2.977018 2.663421
 2.753752 2.318355 2.594653 2.886157 2.967853 2.619835 1.053534 2.530233
 2.8813   2.824559 2.762325 2.070964 2.68601  2.794197 2.720701 2.880792
 2.674431 2.55996  1.212908 1.140615 2.562409 2.004146 2.690754 2.051283
 2.19005  2.21498  2.91548  2.708965 2.853513 2.580872 2.508835 2.896562
 2.911877 2.910733 2.966126 2.613249 2.627031 2.919751 2.494451 1.69427
 1.601236 1.204855 1.052699 2.910345 2.866383 2.913486 2.432886 2.883745
 2.707666 2.919584 2.969205 2.486189 1.642241 1.567101 1.036414 1.649974
 1.118436 2.673638 2.120185 2.34222  2.86099  2.559571 2.424977 1.786841
 1.303878 1.889883 2.984004 2.749268 1.202075 1.871213 2.341133 1.450218
 1.206276 2.81646  1.758394 2.577427 2.052152 2.954996 2.555401 2.108711
 2.915279 1.570089 1.94313  2.903545 1.75375  2.543563 2.39728  2.37464
 2.278644 1.620845 2.061952 2.838969 2.652958 1.27785  1.729824 1.452524
 2.303367 2.948425 2.291846 1.906194 1.834155 2.048582 2.948248 2.869436
 2.293705 2.510583 2.366949 2.615788 2.217267 2.801514 2.188722 2.971351
 2.086093 1.901611 1.977298 2.446872 2.839048 2.21232  2.427689 2.357496
 1.078529 1.064162 1.993101 2.620963 2.95118  2.021446 2.000466 2.5621
 2.96008  2.53915  2.244142 2.253371 2.851664 1.31415  1.321028 2.253998
 2.778079 2.838037 2.814453 2.013782 2.459976 2.643183 2.22399  2.104105
 1.972545 2.286481 2.971588 2.872121 2.109162 2.178889 1.142468 2.047069
 2.843709 2.416044 2.146598 1.766849 1.188089 1.910176 2.956671 2.002796
 2.288604 2.277077 2.138334 2.029634 2.048216 2.8557   2.995599 2.987148
 1.887951 2.786008 2.342323 1.874935 2.213135 2.273548 2.780699 1.687569
 1.989905 1.947405 2.162519 2.923916 2.99448  2.507841 1.836554 1.773265
 2.388168 2.286146 2.487167 2.185938 2.206399 1.952987 2.908757 2.628791
 2.749629 1.595746 2.885178 2.372494 2.153639 2.793561 2.992329 2.927409
 2.706134 2.010684 2.300408 2.119643 2.901924 2.451009 2.754646 2.417635
 2.512719 1.771693 1.57223  2.661556 2.097373 2.061461 1.317729 1.882235
 2.951591 2.067817 2.54527  2.694281 2.821977 2.252472 2.033745 2.595128
 2.759286 1.925064 2.846981 2.650629 2.631565 2.522399 2.784471 1.650505
 1.961347 2.133955 2.684528 2.265973 1.306844 2.258795 2.689929 2.712747
 2.353603 2.598051 1.718156 2.795086 2.030256 2.493448 2.442536 2.003951
 1.34138  2.607335 2.061384 2.696381 1.116068 2.116432 2.031246 2.884212
 2.444599 2.976975 2.766036 1.096455 2.129969 2.019674 2.735297 1.588782
 2.01054  2.689577 2.413156 2.923433 2.882522 1.973499 2.156065 2.992205
 2.944287 1.780746 2.164062 2.247704 2.011656 2.03414  2.746408 2.1239
 2.332074 2.748243 2.303656 1.904732 1.979944 2.407817 2.734314 2.784383
 2.009952 2.008656 1.122127 1.963965 2.319776 1.899116 2.042762 2.129668
 2.182401 2.802696 2.492758 2.733129 2.294067 2.315932 2.802128 2.79606
 2.086898 2.333503 1.653081 2.535315 2.765769 2.215464 2.63165  2.942154
 2.716909 1.83746  1.936479 2.045027 2.760607 2.09449  2.907062 2.399531
 1.521604 2.501683 2.76802  2.742796 2.325623 2.076689 2.271306 2.33361
 2.13683  2.909853 2.490507 1.063449 2.699282 2.4277   2.87599  2.177243
 2.846452 2.19011  2.069267 1.362441 2.09663  2.928234 2.496455 1.70825
 2.262171 2.740633 1.081585 2.587789 2.252653 2.036613 2.609123 1.036159
 1.851262 2.501236 2.031185 2.014194 2.028225 2.037585 1.853314 1.00876
 2.103335 2.060922 2.058687 2.533605 2.457547 2.983851 2.061969 2.450784
 2.972426 2.467002 2.934671 2.043359 2.787589 2.150054 2.977585 2.274491
 1.557287 2.152264 2.08841  2.180047 1.826885 1.754401 1.524428 1.164062
 2.123159 2.259679 2.044326 2.843456 2.864776 2.871137 2.282803 2.020502
 2.020785 2.737149 1.899793 2.274164 1.897796 2.85916  2.340405 2.921576
 2.92711  2.805533 2.902469 2.845961 2.252698 2.02091  2.108163 1.518966
 2.260543 2.522183 2.186322 2.76632  2.071622 1.918251 1.967061 2.964419
 2.640801 2.870152 2.482575 2.290095 2.074843 2.14128  2.334474 2.693859
 2.607747 2.66889  2.921225 1.492834 1.220024 2.667676 2.569075 2.949242
 2.104772 2.871768 2.540949 2.222282 2.04516  2.094184 1.123672 2.049112
 1.880534 1.203754 2.73691  2.736628 2.121909 2.642744 2.387426 1.996638
 2.107854 2.253707 2.393837 2.348745 2.312825 2.490776 2.078082 2.805512
 1.276858 2.396265 2.663866 2.685484 2.055209 2.025479 2.002564 2.385502
 2.465575 2.818502 2.081238 1.368978 1.712848 1.3307   1.961069 2.976509
 2.319648 1.261288 2.76533  2.317734 1.588114 2.549782 2.206276 2.18354
 2.962415 1.99124  2.408561 2.758394 2.956297 1.369529 1.392665 2.630401
 2.869778 1.868212 1.108663 2.907744 2.95801  2.197261 2.048962 2.139196
 2.72989  1.994679 2.403421 2.964319 1.617093 1.631144 2.317459 2.501224
 2.983042 2.323351 1.428289 1.992889 1.562804 1.794825 2.305349 2.576449
 2.754645 2.633855 2.200588 2.499108 2.05687  2.247795 2.239634 2.09283
 2.9673   2.225731 2.178308 2.065752 2.263245 2.443538 2.744994 2.630137
 2.113843 2.821727 2.312528 2.938801 2.050619 1.457758 2.19331  2.028571
 1.455602 2.177896 2.252382 2.668949 2.723953 2.736298 2.722161 2.871016
 2.96405  2.653721 2.859097 1.572036 1.387489 2.941929 2.973569 2.041376
 2.02472  2.133964 2.702457 1.760038 1.996646 2.644094 2.475892 2.941627
 2.998441 2.397284 2.382705 2.176317 2.877743 2.303041 2.323003 1.99953
 1.585183 2.281963 2.561638 2.600217 2.79166  2.08868  2.206119 2.328469
 2.002784 1.975675 2.002076 2.218599 2.392179 2.381164 2.008245 2.155182
 2.969233 2.765063 2.195964 2.619987 2.918113 2.889485 2.939727 1.264234
 1.517912 2.23372  1.475906 2.032883 2.046651 2.667229 2.819934 2.954417
 2.826251 2.95841  2.935157 2.870895 2.869833 1.878251 1.750809 1.168856
 1.443674 2.826036 2.9553   2.774562 2.772027 2.499626 2.108638 2.467548
 2.585942 2.14961  2.938616 2.535154 2.611222 1.800122 1.482722 1.735664
 1.655684 2.598207 2.225149 2.519592 2.111887 2.970983 2.907542 1.451337
 1.537505 1.893428 2.007845 2.487781 2.541785 2.813775 2.562687 2.922511
 2.836055 2.880759 2.766441 2.997524 2.320201 2.181057 1.924632 1.397468
 2.191429 2.100177 2.075321 1.626369 1.263216 1.067909 2.310751 2.294259
 2.57649  2.679664 2.938687 2.654792 2.731368 2.22259  2.432355 2.497548
 2.671238 2.57691  2.341999 2.117121 2.247037 2.244654 2.128574 2.068834
 2.073224 2.145114 2.997951 2.911312 2.159033 2.175276 2.21965  2.203962
 1.947495 2.262292 2.219186 2.314175 2.423291 2.637202 2.974006 2.347942
 2.654076 2.739    2.591292 2.611847 2.766612 2.777165 2.232836 2.571274
 2.49619  2.151335 2.01695  2.927187 1.412566 1.289315 1.624366 1.528331
 2.037042 2.191108 1.431346 1.84199  2.499388 2.230742 2.240757 2.996186
 2.649406 2.525884 2.736647 2.684335 2.425503 1.469384 2.906269 2.808027
 2.636719 2.996717 2.880483 2.885693 2.913452 2.919526 2.724121 2.801992
 2.748971 2.680375]

NCP column unique values:
[3.       1.       4.       3.28926  3.995147 1.72626  2.581015 1.600812
 1.73762  1.10548  2.0846   1.894384 2.857787 3.765526 3.285167 3.691226
 3.156153 1.07976  3.559841 3.891994 3.240578 3.904858 3.11158  3.590039
 2.057935 3.558637 2.000986 3.821168 3.897078 3.092116 3.286431 3.592415
 3.754599 3.566082 3.725797 3.520555 3.731212 1.259803 1.273128 3.304123
 3.647154 3.300666 3.535016 1.717608 2.884479 3.626815 1.473088 3.16645
 3.494849 2.99321  2.127797 3.90779  3.699594 3.179995 1.075553 3.238258
 3.804944 1.630846 3.762778 3.371832 2.705445 3.34175  2.217651 2.893778
 3.502604 3.998766 3.193671 1.69608  2.812377 1.612747 1.082304 1.882158
 2.326233 1.989398 1.735493 2.974568 3.715118 3.489918 3.378859 3.263201
 3.994588 3.24934  3.087544 1.163666 3.409363 3.281391 3.98525  3.207071
 3.471536 3.488342 3.443456 3.03779  3.642802 2.645858 3.420618 2.64155
 3.887906 3.435905 3.747163 2.625475 3.098399 3.12544  3.96981  3.712183
 3.832911 3.576103 3.56544  3.266644 3.433908 3.531038 3.998618 1.226342
 1.060796 3.595761 3.737914 3.697831 3.21043  3.45259  3.205587 1.513835
 2.779379 3.732126 3.937099 3.047959 2.975362 1.394539 3.131032 1.578521
 3.985442 3.623364 3.36313  1.146052 3.981997 1.9154   2.105616 3.714833
 3.292386 1.104642 3.654061 1.296156 2.656588 2.809716 2.77684  1.999014
 2.644692 2.449723 2.794156 1.146794 1.131695 2.488189 3.999591 3.612941
 3.950553 2.951837 2.799979 2.228113 3.042774 1.198643 1.555557 3.987707
 3.995957 1.047197 1.193589 3.390143 3.546352 3.266501 3.554974 2.372311
 2.10601  3.715306 3.376717 1.211606 3.98955  3.171082 3.105007 1.590982
 1.704828 2.725012 2.372339 1.097312 1.068196 1.411685 2.752318 2.737571
 2.973504 2.608055 2.625942 1.411808 1.095223 3.30846  3.821461 2.658639
 2.339614 1.713762 2.743277 3.051804 3.245148 3.563744 3.829101 3.058539
 3.196043 1.391778 1.13715  3.322522 3.269088 2.938135 1.259628 2.965494
 2.845307 3.095663 3.483449 3.156309 3.728377 3.60885  3.370362 2.39007
 1.101404 2.756405 3.054899 3.118013 3.335876 3.205009 3.648194 1.865238
 2.118153 2.961113 2.400943 2.870005 1.030416 2.696051 2.762883 2.401341
 2.298612 3.618722 2.562895 2.849848 2.805436 3.715148 3.788602 1.893811
 1.010319 2.669766 1.322087 2.041558 2.468421 2.110937 3.071028 3.292956
 2.283673 1.124977 2.9948   2.983297 1.890213 1.888067 2.256119 2.6648
 2.547086 2.812283 2.278652 1.240046 1.660768 2.597608 2.044035 2.038373
 1.474836 3.986652 2.720642 1.976744 2.679724 1.619796 2.59257  1.546665
 3.339914 3.884861 2.358298 1.802305 2.7976   2.627173 1.032887 3.014808
 2.271734 2.122545 2.902766 2.687502 1.178708 2.279546 2.677693 3.53009
 1.835543 2.853676 2.337035 1.631184 1.005391 3.250467 2.948721 1.80993
 1.94671  2.9796   2.994198 2.579291 2.449067 1.532833 2.961706 1.152521
 1.729553 1.346987 1.977221 2.443812 2.491315 2.843319 2.157164 2.601675
 1.171027 3.362758 1.672706 2.714115 2.521546 1.338033 1.081805 3.087119
 2.909117 1.466393 1.471053 2.983201 2.783336 1.863012 3.053598 3.165837
 2.741413 1.058123 2.997414 1.672958 1.680838 3.070386 2.608416 1.599464
 2.815255 2.395785 2.844138 2.716106 1.402771 2.865657 1.836226 2.884848
 2.375026 2.9774   2.693646 2.832018 2.270163 2.646717 1.193729 1.477581
 3.209508 2.756622 2.658478 1.971472 1.818026 1.820779 1.724887 3.129155
 3.856434 2.753418 2.116195 2.049908 1.044628 2.98212  1.009426 2.667711
 3.000974 2.698883 2.598079 2.837388 2.946063 1.873484 2.473911 1.79558
 2.623079 2.174968 2.676148 3.394788 2.137068 2.937607 1.313403 2.113575
 2.092179 2.974204 1.001633 1.2919   1.139317 2.029858 2.977543 1.476204
 2.57038  2.879541 1.458507 1.105617 1.854536 1.08687  1.25535  2.870661
 1.482103 1.81698  2.582591 2.164839 2.141839 2.877583 2.95833  2.119826
 2.992606 2.050121 1.923607 2.27374  1.418985 1.320768 2.964024 2.933409
 2.962004 1.271624 1.00061  1.068443 2.952821 1.851088 2.119682 2.970675
 2.966803 1.508685 2.209314 1.114564 2.036794 2.988539 1.630506 2.977999
 2.733077 2.427137 1.867836 1.548407 2.937989 1.237454 1.169173 2.391753
 2.475444 2.478794 2.070033 2.282392 1.049534 1.66338  1.672751 1.734762
 1.92822  2.475228 2.093831 1.231915 1.374791 1.326982 2.900915 1.317884
 2.977909 1.355752 1.015488 2.986172 2.993623 1.001383 1.001542 2.590283
 1.773916 2.989112 1.496776 2.994046 1.000283 1.000414 1.135278 2.463113
 1.782109 2.376374 2.976098 2.968098 1.792695 1.116401 2.984523 2.978103
 1.578751 1.874532 2.735706 1.014916 2.622055 2.806566 1.355354 1.478334
 1.130751 1.099151 2.358455 1.706551 1.24884  1.250548 1.202179 1.194815
 2.880817 2.918124 1.073421 1.416309 2.18162  2.152733 1.046144 1.974233
 2.880794 2.765213 2.967089 2.37985  2.655265 1.941307 1.709546 2.883984
 2.935381 2.961192 2.973476 2.392811 1.293342 2.930044 2.129909 2.831771
 2.595126 2.52751  2.120936 1.468948 3.990925 2.834253 3.734323 2.049565
 2.272214 2.218285 1.418833 1.109956 3.914454 3.169089 2.419656 2.175432
 2.806298 2.987652 2.842848 1.134321 1.924168 2.701689 2.992903 2.658837
 2.80742  1.834472 2.123138 1.265463 1.340361 3.989492 2.650088 2.89292
 2.938902 2.986637 2.701521 2.014671 1.971659 1.311797 1.262831 3.770379
 2.87747  2.175153 2.13229  2.993634 2.999346 2.976211 2.842035 1.09749
 1.91863  2.510135 2.65772  2.604998 2.567567 2.434347 1.845858 1.627555
 1.569176 2.371658 2.378211 2.301129 2.454432 2.915921 2.992083 2.849347
 2.954446 3.755976 2.902639 2.372705 2.100918 2.272801 2.692889 2.280545
 2.675411 1.487674 1.02075  1.240424 1.154318 3.219347 3.656401 3.220181
 2.850948 2.187145 2.415522 2.138375 1.077331 2.888193 2.574108 2.740492
 2.956422 2.749334 2.993856 2.993084 2.989791 2.920373 2.911568 1.134042
 1.120102 2.040582 2.015675 2.711238 2.695396 2.996834 2.996444 2.894142
 2.683061 2.806341 2.791366 1.703299 1.685134 2.269799 2.142328 1.437959
 1.343117 1.213431 1.089048]

SCC column unique values:
['no' 'yes']

SMOKE column unique values:
['no' 'yes']

CH2O column unique values:
[2.       3.       1.       ... 2.054193 2.852339 2.863513]

family_history_with_overweight column unique values:
['yes' 'no']

FAF column unique values:
[0.       3.       2.       ... 1.414209 1.139107 1.026452]

TUE column unique values:
[1.       0.       2.       ... 0.646288 0.586035 0.714137]

CAEC column unique values:
['Sometimes' 'Frequently' 'Always' 'no']

MTRANS column unique values:
['Public_Transportation' 'Walking' 'Automobile' 'Motorbike' 'Bike']

NObeyesdad column unique values:
['Normal_Weight' 'Overweight_Level_I' 'Overweight_Level_II'
 'Obesity_Type_I' 'Insufficient_Weight' 'Obesity_Type_II'
 'Obesity_Type_III']

BMI column unique values:
[24.39 24.24 23.77 ... 44.45 43.88 44.04]
['no' 'Sometimes' 'Frequently' 'Always']

FAVC column unique values:
['no' 'yes']

FCVC column unique values:
[2.       3.       1.       2.450218 2.880161 2.00876  2.596579 2.591439
 2.392665 1.123939 2.027574 2.658112 2.88626  2.714447 2.750715 1.4925
 2.205439 2.059138 2.310423 2.823179 2.052932 2.596364 2.767731 2.815157
 2.737762 2.568063 2.524428 2.971574 1.0816   1.270448 1.344854 2.959658
 2.725282 2.844607 2.44004  2.432302 2.592247 2.449267 2.929889 2.015258
 1.031149 1.592183 1.21498  1.522001 2.703436 2.362918 2.14084  2.5596
 2.336044 1.813234 2.724285 2.71897  1.133844 1.757466 2.979383 2.204914
 2.927218 2.88853  2.890535 2.530066 2.241606 1.003566 2.652779 2.897899
 2.483979 2.945967 2.478891 2.784464 1.005578 2.938031 2.842102 1.889199
 2.943749 2.33998  1.950742 2.277436 2.371338 2.984425 2.977018 2.663421
 2.753752 2.318355 2.594653 2.886157 2.967853 2.619835 1.053534 2.530233
 2.8813   2.824559 2.762325 2.070964 2.68601  2.794197 2.720701 2.880792
 2.674431 2.55996  1.212908 1.140615 2.562409 2.004146 2.690754 2.051283
 2.19005  2.21498  2.91548  2.708965 2.853513 2.580872 2.508835 2.896562
 2.911877 2.910733 2.966126 2.613249 2.627031 2.919751 2.494451 1.69427
 1.601236 1.204855 1.052699 2.910345 2.866383 2.913486 2.432886 2.883745
 2.707666 2.919584 2.969205 2.486189 1.642241 1.567101 1.036414 1.649974
 1.118436 2.673638 2.120185 2.34222  2.86099  2.559571 2.424977 1.786841
 1.303878 1.889883 2.984004 2.749268 1.202075 1.871213 2.341133 1.450218
 1.206276 2.81646  1.758394 2.577427 2.052152 2.954996 2.555401 2.108711
 2.915279 1.570089 1.94313  2.903545 1.75375  2.543563 2.39728  2.37464
 2.278644 1.620845 2.061952 2.838969 2.652958 1.27785  1.729824 1.452524
 2.303367 2.948425 2.291846 1.906194 1.834155 2.048582 2.948248 2.869436
 2.293705 2.510583 2.366949 2.615788 2.217267 2.801514 2.188722 2.971351
 2.086093 1.901611 1.977298 2.446872 2.839048 2.21232  2.427689 2.357496
 1.078529 1.064162 1.993101 2.620963 2.95118  2.021446 2.000466 2.5621
 2.96008  2.53915  2.244142 2.253371 2.851664 1.31415  1.321028 2.253998
 2.778079 2.838037 2.814453 2.013782 2.459976 2.643183 2.22399  2.104105
 1.972545 2.286481 2.971588 2.872121 2.109162 2.178889 1.142468 2.047069
 2.843709 2.416044 2.146598 1.766849 1.188089 1.910176 2.956671 2.002796
 2.288604 2.277077 2.138334 2.029634 2.048216 2.8557   2.995599 2.987148
 1.887951 2.786008 2.342323 1.874935 2.213135 2.273548 2.780699 1.687569
 1.989905 1.947405 2.162519 2.923916 2.99448  2.507841 1.836554 1.773265
 2.388168 2.286146 2.487167 2.185938 2.206399 1.952987 2.908757 2.628791
 2.749629 1.595746 2.885178 2.372494 2.153639 2.793561 2.992329 2.927409
 2.706134 2.010684 2.300408 2.119643 2.901924 2.451009 2.754646 2.417635
 2.512719 1.771693 1.57223  2.661556 2.097373 2.061461 1.317729 1.882235
 2.951591 2.067817 2.54527  2.694281 2.821977 2.252472 2.033745 2.595128
 2.759286 1.925064 2.846981 2.650629 2.631565 2.522399 2.784471 1.650505
 1.961347 2.133955 2.684528 2.265973 1.306844 2.258795 2.689929 2.712747
 2.353603 2.598051 1.718156 2.795086 2.030256 2.493448 2.442536 2.003951
 1.34138  2.607335 2.061384 2.696381 1.116068 2.116432 2.031246 2.884212
 2.444599 2.976975 2.766036 1.096455 2.129969 2.019674 2.735297 1.588782
 2.01054  2.689577 2.413156 2.923433 2.882522 1.973499 2.156065 2.992205
 2.944287 1.780746 2.164062 2.247704 2.011656 2.03414  2.746408 2.1239
 2.332074 2.748243 2.303656 1.904732 1.979944 2.407817 2.734314 2.784383
 2.009952 2.008656 1.122127 1.963965 2.319776 1.899116 2.042762 2.129668
 2.182401 2.802696 2.492758 2.733129 2.294067 2.315932 2.802128 2.79606
 2.086898 2.333503 1.653081 2.535315 2.765769 2.215464 2.63165  2.942154
 2.716909 1.83746  1.936479 2.045027 2.760607 2.09449  2.907062 2.399531
 1.521604 2.501683 2.76802  2.742796 2.325623 2.076689 2.271306 2.33361
 2.13683  2.909853 2.490507 1.063449 2.699282 2.4277   2.87599  2.177243
 2.846452 2.19011  2.069267 1.362441 2.09663  2.928234 2.496455 1.70825
 2.262171 2.740633 1.081585 2.587789 2.252653 2.036613 2.609123 1.036159
 1.851262 2.501236 2.031185 2.014194 2.028225 2.037585 1.853314 1.00876
 2.103335 2.060922 2.058687 2.533605 2.457547 2.983851 2.061969 2.450784
 2.972426 2.467002 2.934671 2.043359 2.787589 2.150054 2.977585 2.274491
 1.557287 2.152264 2.08841  2.180047 1.826885 1.754401 1.524428 1.164062
 2.123159 2.259679 2.044326 2.843456 2.864776 2.871137 2.282803 2.020502
 2.020785 2.737149 1.899793 2.274164 1.897796 2.85916  2.340405 2.921576
 2.92711  2.805533 2.902469 2.845961 2.252698 2.02091  2.108163 1.518966
 2.260543 2.522183 2.186322 2.76632  2.071622 1.918251 1.967061 2.964419
 2.640801 2.870152 2.482575 2.290095 2.074843 2.14128  2.334474 2.693859
 2.607747 2.66889  2.921225 1.492834 1.220024 2.667676 2.569075 2.949242
 2.104772 2.871768 2.540949 2.222282 2.04516  2.094184 1.123672 2.049112
 1.880534 1.203754 2.73691  2.736628 2.121909 2.642744 2.387426 1.996638
 2.107854 2.253707 2.393837 2.348745 2.312825 2.490776 2.078082 2.805512
 1.276858 2.396265 2.663866 2.685484 2.055209 2.025479 2.002564 2.385502
 2.465575 2.818502 2.081238 1.368978 1.712848 1.3307   1.961069 2.976509
 2.319648 1.261288 2.76533  2.317734 1.588114 2.549782 2.206276 2.18354
 2.962415 1.99124  2.408561 2.758394 2.956297 1.369529 1.392665 2.630401

In [188]:
# Categorical to Numerical Mapping
mapping = {
    'Gender': {
        'Female': 0,
        'Male': 1
    },
    'CALC': {
        'no': 0,
        'Sometimes': 1,
        'Frequently': 2,
        'Always': 3
    },
    'FAVC': {
        'no': 0,
        'yes': 1,
    },
    'SCC': {
        'no': 0,
        'yes': 1,
    },
    'SMOKE': {
        'no': 0,
        'yes': 1,
    },
    'family_history_with_overweight': {
        'no': 0,
        'yes': 1
    },
    'CAEC': {
        'Sometimes': 3,
        'Frequently': 2,
        'Always': 4,
        'no': 0
    },
    'MTRANS': {
        'Public_Transportation': 0,
        'Walking': 1,
        'Automobile': 2,
        'Motorbike': 3,
        'Bike': 4
    },
    'NObeyesdad': {
        'Normal_Weight': 0,
        'Overweight_Level_I': 1,
        'Overweight_Level_II': 2,
        'Obesity_Type_I': 3,
        'Insufficient_Weight': 4,
        'Obesity_Type_II': 5,
        'Obesity_Type_III': 6
    }
}

# Apply Mapping to DataFrame
df = df.replace(mapping)

In [189]:
# Display Final Dataset
df

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad,BMI
0,21,0,1.62,64.00,0,0,2.0,3.0,0,0,2.000000,1,0.000000,1.000000,3,0,0,24.39
1,21,0,1.52,56.00,1,0,3.0,3.0,1,1,3.000000,1,3.000000,0.000000,3,0,0,24.24
2,23,1,1.80,77.00,2,0,2.0,3.0,0,0,2.000000,1,2.000000,1.000000,3,0,0,23.77
3,27,1,1.80,87.00,2,0,3.0,3.0,0,0,2.000000,0,2.000000,0.000000,3,1,1,26.85
4,22,1,1.78,89.80,1,0,2.0,1.0,0,0,2.000000,0,0.000000,0.000000,3,0,2,28.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,20,0,1.71,131.41,1,1,3.0,3.0,0,0,1.728139,1,1.676269,0.906247,3,0,6,44.94
2107,21,0,1.75,133.74,1,1,3.0,3.0,0,0,2.005130,1,1.341390,0.599270,3,0,6,43.67
2108,22,0,1.75,133.69,1,1,3.0,3.0,0,0,2.054193,1,1.414209,0.646288,3,0,6,43.65
2109,24,0,1.74,133.35,1,1,3.0,3.0,0,0,2.852339,1,1.139107,0.586035,3,0,6,44.04
2110,23,0,1.74,133.47,1,1,3.0,3.0,0,0,2.863513,1,1.026452,0.714137,3,0,6,44.08

In [190]:
# Final Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2087 entries, 0 to 2110
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2087 non-null   int64
 1   Gender                          2087 non-null   int64
 2   Height                          2087 non-null   float64
 3   Weight                          2087 non-null   float64
 4   CALC                            2087 non-null   int64
 5   FAVC                            2087 non-null   int64
 6   FCVC                            2087 non-null   float64
 7   NCP                             2087 non-null   float64
 8   SCC                             2087 non-null   int64
 9   SMOKE                           2087 non-null   int64
 10  CH2O                            2087 non-null   float64
 11  family_history_with_overweight  2087 non-null   int64
 12  FAF                             2087 non-null   float64
 13  TUE                             2087 non-null   float64
 14  CAEC                            2087 non-null   int64
 15  MTRANS                          2087 non-null   int64
 16  NObeyesdad                      2087 non-null   int64
 17  BMI                             2087 non-null   float64
dtypes: float64(8), int64(10)
memory usage: 309.8 KB

In [191]:
# Check Column Ranges for Scaling Decision
print("Column Min-Max Values:")
print("-" * 50)
for col in df.columns:
    if df[col].dtype in ['float64', 'int64']:
        print(f"{col:30} | Min: {df[col].min():8.2f} | Max: {df[col].max():8.2f} | Range: {df[col].max() - df[col].min():8.2f}")

Column Min-Max Values:
--------------------------------------------------
Age                            | Min:    14.00 | Max:    61.00 | Range:    47.00
Gender                         | Min:     0.00 | Max:     1.00 | Range:     1.00
Height                         | Min:     1.45 | Max:     1.98 | Range:     0.53
Weight                         | Min:    39.00 | Max:   173.00 | Range:   134.00
CALC                           | Min:     0.00 | Max:     3.00 | Range:     3.00
FAVC                           | Min:     0.00 | Max:     1.00 | Range:     1.00
FCVC                           | Min:     1.00 | Max:     3.00 | Range:     2.00
NCP                            | Min:     1.00 | Max:     4.00 | Range:     3.00
SCC                            | Min:     0.00 | Max:     1.00 | Range:     1.00
SMOKE                          | Min:     0.00 | Max:     1.00 | Range:     1.00
CH2O                           | Min:     1.00 | Max:     3.00 | Range:     2.00
family_history_with_overweight | Min:     0.00 | Max:     1.00 | Range:     1.00
FAF                            | Min:     0.00 | Max:     3.00 | Range:     3.00
TUE                            | Min:     0.00 | Max:     2.00 | Range:     2.00
CAEC                           | Min:     0.00 | Max:     4.00 | Range:     4.00
MTRANS                         | Min:     0.00 | Max:     4.00 | Range:     4.00
NObeyesdad                     | Min:     0.00 | Max:     6.00 | Range:     6.00
BMI                            | Min:    13.00 | Max:    50.82 | Range:    37.82

In [192]:
# Feature Scaling with StandardScaler
from sklearn.preprocessing import StandardScaler

# Separate Features (X) and Target (y)
X = df.drop('NObeyesdad', axis=1)  # Features (input)
y = df['NObeyesdad']  # Target (output)

print("Features (X) columns:")
print(X.columns.tolist())
print(f"\nFeatures shape: {X.shape}")
print(f"Target shape: {y.shape}")

# Apply StandardScaler to Features Only
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert Scaled Data to DataFrame
X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

Features (X) columns:
['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP', 'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE', 'CAEC', 'MTRANS', 'BMI']

Features shape: (2087, 17)
Target shape: (2087,)

In [193]:
# Machine Learning Pipeline Setup
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')

# Train/Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled_df, y, test_size=0.2, random_state=42, stratify=y
)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

# Target Distribution in Training Set
print(f"\nTarget Distribution (y_train):")
print(y_train.value_counts().sort_index())

X_train shape: (1669, 17)
X_test shape: (418, 17)
y_train shape: (1669,)
y_test shape: (418,)

Target Distribution (y_train):
NObeyesdad
0    225
1    221
2    232
3    281
4    214
5    237
6    259
Name: count, dtype: int64
NObeyesdad
0    225
1    221
2    232
3    281
4    214
5    237
6    259
Name: count, dtype: int64

In [194]:
# Model Comparison and Training
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42),
    'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
    'SVM': SVC(random_state=42),
    'KNN': KNeighborsClassifier(n_neighbors=5)
}

# Store Model Performance
results = {}

print("🚀 Model Training Started...")
print("=" * 50)

for name, model in models.items():
    # Train Model
    model.fit(X_train, y_train)
    
    # Make Predictions
    y_pred = model.predict(X_test)
    
    # Calculate Accuracy
    accuracy = accuracy_score(y_test, y_pred)
    results[name] = accuracy
    
    print(f"{name:20} | Accuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

print("=" * 50)
print(f"🏆 Best Model: {max(results, key=results.get)} - Accuracy: {max(results.values()):.4f}")

🚀 Model Training Started...
==================================================
Random Forest        | Accuracy: 0.9928 (99.28%)
Logistic Regression  | Accuracy: 0.9115 (91.15%)
SVM                  | Accuracy: 0.9234 (92.34%)
KNN                  | Accuracy: 0.8301 (83.01%)
==================================================
🏆 Best Model: Random Forest - Accuracy: 0.9928
Random Forest        | Accuracy: 0.9928 (99.28%)
Logistic Regression  | Accuracy: 0.9115 (91.15%)
SVM                  | Accuracy: 0.9234 (92.34%)
KNN                  | Accuracy: 0.8301 (83.01%)
==================================================
🏆 Best Model: Random Forest - Accuracy: 0.9928

In [195]:
# Detailed Analysis of Best Model
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

# Make Predictions with Best Model
y_pred_best = best_model.predict(X_test)

print(f"🔍 {best_model_name} - Detailed Analysis")
print("=" * 50)

# Classification Report
print("\n📊 Classification Report:")
print(classification_report(y_test, y_pred_best))

# Confusion Matrix
print("\n🎯 Confusion Matrix:")
cm = confusion_matrix(y_test, y_pred_best)
print(cm)

# Obesity Class Labels
obesity_classes = {
    0: 'Normal_Weight',
    1: 'Overweight_Level_I', 
    2: 'Overweight_Level_II',
    3: 'Obesity_Type_I',
    4: 'Insufficient_Weight',
    5: 'Obesity_Type_II',
    6: 'Obesity_Type_III'
}

print("\n🏷️ Class Labels:")
for key, value in obesity_classes.items():
    print(f"{key}: {value}")

🔍 Random Forest - Detailed Analysis
==================================================

📊 Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        57
           1       1.00      0.96      0.98        55
           2       1.00      1.00      1.00        58
           3       1.00      1.00      1.00        70
           4       1.00      1.00      1.00        53
           5       0.98      1.00      0.99        60
           6       1.00      0.98      0.99        65

    accuracy                           0.99       418
   macro avg       0.99      0.99      0.99       418
weighted avg       0.99      0.99      0.99       418


🎯 Confusion Matrix:
[[57  0  0  0  0  0  0]
 [ 2 53  0  0  0  0  0]
 [ 0  0 58  0  0  0  0]
 [ 0  0  0 70  0  0  0]
 [ 0  0  0  0 53  0  0]
 [ 0  0  0  0  0 60  0]
 [ 0  0  0  0  0  1 64]]

🏷️ Class Labels:
0: Normal_Weight
1: Overweight_Level_I
2: Overweight_Level_II
3: Obesity_Type_I
4: Insufficient_Weight
5: Obesity_Type_II
6: Obesity_Type_III

In [204]:
# Fixed Obesity Prediction Function with Random Forest
def predict_obesity_level(gender, age, height, weight, family_history, favc, fcvc, ncp, caec, smoke, ch2o, scc, faf, tue, calc, mtrans):
    """
    Predicts obesity level based on personal characteristics
    
    Parameters:
    - gender: 'Male' or 'Female'
    - age: Age in years (int)
    - height: Height in meters (float, e.g., 1.70)
    - weight: Weight in kg (float, e.g., 65.5)
    - family_history: 'yes' or 'no'
    - favc: 'yes' or 'no' (Do you eat high caloric food frequently?)
    - fcvc: 1-3 (Do you usually eat vegetables in your meals?)
    - ncp: 1-4 (How many main meals do you have daily?)
    - caec: 'no', 'Sometimes', 'Frequently', 'Always' (Do you eat food between meals?)
    - smoke: 'yes' or 'no'
    - ch2o: 1-3 (How much water do you drink daily?)
    - scc: 'yes' or 'no' (Do you monitor calories?)
    - faf: 0-3 (How often do you have physical activity?)
    - tue: 0-2 (Time using technology devices?)
    - calc: 'no', 'Sometimes', 'Frequently', 'Always' (How often do you drink alcohol?)
    - mtrans: 'Public_Transportation', 'Walking', 'Automobile', 'Motorbike', 'Bike'
    
    Returns:
    - Predicted obesity level and probability
    """
    
    # Calculate BMI
    bmi = round(weight / (height ** 2), 2)
    
    # Create input data in the EXACT order the model expects
    # Order: ['Age', 'Gender', 'Height', 'Weight', 'CALC', 'FAVC', 'FCVC', 'NCP', 'SCC', 'SMOKE', 'CH2O', 'family_history_with_overweight', 'FAF', 'TUE', 'CAEC', 'MTRANS', 'BMI']
    input_data = {
        'Age': age,
        'Gender': 1 if gender.lower() == 'male' else 0,
        'Height': height,
        'Weight': weight,
        'CALC': {'no': 0, 'sometimes': 1, 'frequently': 2, 'always': 3}[calc.lower()],
        'FAVC': 1 if favc.lower() == 'yes' else 0,
        'FCVC': fcvc,
        'NCP': ncp,
        'SCC': 1 if scc.lower() == 'yes' else 0,
        'SMOKE': 1 if smoke.lower() == 'yes' else 0,
        'CH2O': ch2o,
        'family_history_with_overweight': 1 if family_history.lower() == 'yes' else 0,
        'FAF': faf,
        'TUE': tue,
        'CAEC': {'no': 0, 'sometimes': 3, 'frequently': 2, 'always': 4}[caec.lower()],
        'MTRANS': {'public_transportation': 0, 'walking': 1, 'automobile': 2, 'motorbike': 3, 'bike': 4}[mtrans.lower()],
        'BMI': bmi
    }
    
    # Convert to DataFrame with correct column order
    input_df = pd.DataFrame([input_data])
    
    # Ensure the column order matches exactly what the model expects
    input_df = input_df[X.columns]
    
    # Scale the input data
    input_scaled = scaler.transform(input_df)
    
    # Make prediction
    prediction = best_model.predict(input_scaled)[0]
    prediction_proba = best_model.predict_proba(input_scaled)[0]
    
    # Convert prediction to class name
    obesity_classes = {
        0: 'Normal Weight',
        1: 'Overweight Level I', 
        2: 'Overweight Level II',
        3: 'Obesity Type I',
        4: 'Insufficient Weight',
        5: 'Obesity Type II',
        6: 'Obesity Type III'
    }
    
    predicted_class = obesity_classes[prediction]
    confidence = prediction_proba[prediction] * 100
    
    print(f"🎯 Prediction Results:")
    print(f"BMI: {bmi}")
    print(f"Predicted Obesity Level: {predicted_class}")
    print(f"Confidence: {confidence:.1f}%")
    print(f"\nAll Class Probabilities:")
    for i, prob in enumerate(prediction_proba):
        print(f"  {obesity_classes[i]}: {prob*100:.1f}%")
    
    return predicted_class, confidence

print("✅ Fixed Obesity Prediction Function Ready!")
print("✅ Feature order now matches the trained model!")

✅ Fixed Obesity Prediction Function Ready!
✅ Feature order now matches the trained model!

In [208]:
# Save Model and Scaler for Web API
import pickle
import joblib

# Save the trained model
joblib.dump(best_model, 'obesity_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

print("✅ Model and Scaler saved!")
print("- obesity_model.pkl: Trained Random Forest model")
print("- scaler.pkl: Fitted StandardScaler")

✅ Model and Scaler saved!
- obesity_model.pkl: Trained Random Forest model
- scaler.pkl: Fitted StandardScaler